# Generated by Django 5.0.2 on 2024-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='end_date',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='college',
            name='start_date',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='organization',
            field=models.TextField(blank=True, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='time_duration',
            field=models.JSONField(blank=True, null=True, verbose_name='Time Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_duration',
            field=models.JSONField(blank=True, null=True, verbose_name='Time Duration'),
        ),
    ]
