# Generated by Django 5.0.2 on 2024-02-25 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="Applicant's Resume")),
            ],
        ),
    ]
